-- Make employer_id nullable temporarily to allow sample data insertion
-- This is safe because RLS policies will still control access

ALTER TABLE public.jobs ALTER COLUMN employer_id DROP NOT NULL;

-- Insert sample jobs without employer_id (they will be system/demo jobs)
INSERT INTO public.jobs (
  title, company, company_logo, location, job_type, salary_min, salary_max, 
  description, requirements, benefits, skills, experience_level, status
) VALUES
(
  'Senior Frontend Developer',
  'TechFlow Inc.',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/react.svg',
  'San Francisco, CA',
  'remote',
  120000,
  180000,
  'We are looking for a Senior Frontend Developer to join our growing team. You will be responsible for building and maintaining our web applications, collaborating with designers and backend developers to create seamless user experiences.',
  ARRAY['5+ years of experience with React', 'Strong TypeScript skills', 'Experience with modern CSS frameworks', 'Understanding of web performance optimization', 'Excellent communication skills'],
  ARRAY['Competitive salary and equity', 'Remote-first culture', 'Health, dental, and vision insurance', 'Unlimited PTO', '401(k) matching'],
  ARRAY['React', 'TypeScript', 'Tailwind CSS'],
  'Senior',
  'active'
),
(
  'Product Designer',
  'DesignHub',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/figma.svg',
  'New York, NY',
  'full-time',
  90000,
  130000,
  'Join our design team to create beautiful and intuitive user experiences. You will work closely with product managers and engineers to bring ideas to life.',
  ARRAY['3+ years of product design experience', 'Proficiency in Figma', 'Strong portfolio demonstrating UI/UX skills', 'Experience with user research', 'Ability to work in a fast-paced environment'],
  ARRAY['Competitive compensation', 'Flexible work hours', 'Professional development budget', 'Modern office in Manhattan', 'Team retreats'],
  ARRAY['Figma', 'UI/UX', 'Prototyping'],
  'Mid Level',
  'active'
),
(
  'Backend Engineer',
  'CloudScale',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/amazonaws.svg',
  'Seattle, WA',
  'full-time',
  140000,
  200000,
  'Build and scale our cloud infrastructure to support millions of users worldwide.',
  ARRAY['5+ years of backend development experience', 'Strong Node.js skills', 'Experience with AWS services', 'Database design and optimization', 'Microservices architecture experience'],
  ARRAY['Top-tier compensation', 'Significant equity', 'Premium health benefits', 'Unlimited PTO', 'Relocation assistance'],
  ARRAY['Node.js', 'AWS', 'PostgreSQL'],
  'Senior',
  'active'
),
(
  'Mobile Developer',
  'AppWorks',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/apple.svg',
  'Los Angeles, CA',
  'full-time',
  100000,
  140000,
  'Build cross-platform mobile applications for our diverse client base.',
  ARRAY['3+ years of mobile development', 'React Native proficiency', 'Understanding of iOS and Android platforms', 'App store deployment experience', 'Performance optimization skills'],
  ARRAY['Competitive pay', 'Creative environment', 'Latest tech stack', 'Team events', 'Learning budget'],
  ARRAY['React Native', 'iOS', 'Android'],
  'Mid Level',
  'active'
),
(
  'Data Scientist',
  'TechFlow Inc.',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/python.svg',
  'Austin, TX',
  'full-time',
  130000,
  170000,
  'We are seeking a Data Scientist to help us extract insights from large datasets and build predictive models.',
  ARRAY['Masters or PhD in a quantitative field', 'Strong Python and SQL skills', 'Experience with machine learning frameworks', 'Ability to communicate complex findings', 'Experience with big data technologies'],
  ARRAY['Competitive salary', 'Stock options', 'Health benefits', 'Learning stipend', 'Gym membership'],
  ARRAY['Python', 'Machine Learning', 'SQL'],
  'Senior',
  'active'
),
(
  'DevOps Engineer',
  'CloudScale',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/docker.svg',
  'Denver, CO',
  'full-time',
  110000,
  150000,
  'Join our infrastructure team to build and maintain our deployment pipelines.',
  ARRAY['4+ years of DevOps experience', 'Kubernetes expertise', 'CI/CD pipeline experience', 'Scripting skills (Python, Bash)', 'Cloud platform experience'],
  ARRAY['Competitive salary', 'Hybrid work model', 'Health benefits', 'Stock options', '401k matching'],
  ARRAY['Kubernetes', 'Docker', 'CI/CD'],
  'Mid Level',
  'active'
),
(
  'UX Researcher',
  'DesignHub',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/sketch.svg',
  'Chicago, IL',
  'contract',
  70000,
  95000,
  'Conduct user research to inform product decisions and improve user experience.',
  ARRAY['2+ years of UX research experience', 'Experience with various research methods', 'Strong analytical skills', 'Excellent presentation skills', 'Empathy for users'],
  ARRAY['Competitive hourly rate', 'Flexible schedule', 'Remote work options', 'Professional development', 'Great team culture'],
  ARRAY['User Testing', 'Surveys', 'Analytics'],
  'Mid Level',
  'active'
),
(
  'Junior React Developer',
  'AppWorks',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/react.svg',
  'Remote',
  'remote',
  60000,
  85000,
  'Great opportunity for a junior developer to grow with our team. Mentorship and learning opportunities available.',
  ARRAY['1+ years of React experience', 'Understanding of JavaScript/TypeScript', 'Eagerness to learn', 'Good communication skills', 'Portfolio of personal projects'],
  ARRAY['Mentorship program', 'Remote-first', 'Learning budget', 'Flexible hours', 'Career growth path'],
  ARRAY['React', 'JavaScript', 'CSS'],
  'Entry Level',
  'active'
),
(
  'Marketing Manager',
  'GrowthLabs',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/googleanalytics.svg',
  'Remote',
  'remote',
  80000,
  110000,
  'Lead our marketing efforts and help us scale our brand presence across multiple channels.',
  ARRAY['4+ years of marketing experience', 'Strong understanding of digital marketing', 'Experience with marketing analytics tools', 'Excellent writing skills', 'Team leadership experience'],
  ARRAY['Remote work', 'Flexible schedule', 'Performance bonuses', 'Health insurance', 'Home office stipend'],
  ARRAY['SEO', 'Content Strategy', 'Analytics'],
  'Senior',
  'active'
),
(
  'Sales Representative',
  'SalesForce Pro',
  'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/salesforce.svg',
  'Boston, MA',
  'full-time',
  60000,
  100000,
  'Drive sales growth by building relationships with enterprise clients.',
  ARRAY['2+ years of B2B sales experience', 'CRM proficiency', 'Strong communication skills', 'Target-driven mindset', 'Travel flexibility'],
  ARRAY['Uncapped commission', 'Base salary', 'Health benefits', 'Car allowance', 'Sales training'],
  ARRAY['B2B Sales', 'CRM', 'Negotiation'],
  'Mid Level',
  'active'
);